services:
  - type: web
    name: web-automi
    env: docker
    region: ohio
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: GROQ_API_KEY
        sync: false
      - key: REUSE_BROWSER
        value: "0"
    disk:
      name: sqlite-data
      mountPath: /app/data
      sizeGB: 1
